version: "3.8"
services:
  app:
    build: ./docker/php
    volumes:
      - ./app:/work
  nginx:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./app:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  db:
    image: postgres:13-alpine
    build: ./docker/psql
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: 'metis'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'metis'
    volumes:
      - ./docker/psql/data:/var/lib/postgresql/data
      - ./docker/psql/initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
